### ISSUE TITLE
Build-time mirroring in BCD

### ISSUE THREAD

**Issue by foolip** [openwebdocs/project#101]
https://github.com/mdn/browser-compat-data/issues/15083 is a proposal to simplify maintenance of BCD by drastically reducing the amount of manually maintained data, in the typical case inferring the data for 5 browsers (Chrome Android, Edge, Opera, Opera Android, WebView Android) from the Chrome data.

This project would consistent of multiple parts:
- [x] The schema and code changes to support mirroring (#109)
- [x] Replacing manual data with mirrored data where they would match (#110)
- [ ] Vetting places where manual data remains and is likely to be wrong

There would be no change to the published packages, which makes it all simpler / less risky.

**Comment by foolip** [comment]
@queengooborg can you add the "proposed for Q3 2022" label for this?

**Comment by queengooborg** [comment]
I actually don't have editor access for this repository, so I can't add labels!

**Comment by foolip** [comment]
@teoli2003 how about you?

**Comment by teoli2003** [comment]
I have, so I added the label 14 hours ago :-)

**Comment by foolip** [comment]
Oops, thanks and sorry for the noise!

**Comment by jpmedley** [comment]
It's my understanding that Samsung is not a perfect mirror of Chrome. They fork from a version earlier than stable and sometimes merge features from later versions. I would suggest confirming that all of the Chromium browsers can be mirrored.

**Comment by queengooborg** [comment]
Phase one of this project has now been implemented in https://github.com/mdn/browser-compat-data/pull/16401!  There are some bugs to work out before we perform a mass conversion of existing data to use mirroring.

I've taken off the "proposed for Q3'22" label and added this as a Q2'22 project because we're already working on it now.

**Comment by Elchi3** [comment]
I'd like to close this project as complete since BCD has mirroring now. Please open a new OWD project proposal if there is a follow up project from here.
