### ISSUE TITLE
Project: HTML Attributes

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#114]
* [Attributes for input elements](https://discourse.mozilla.org/t/attributes-for-input-elements/43899) @wbamberg started a discussion on input attributes, suggesting giving each input element its own "Attributes" list including all the attributes it supports (apart from the [real global ones](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes)) and scrap the "Supported common attributes" row in the blue box. 
* [Attributes documentation for HTML input elements is confusing](https://github.com/mdn/content/issues/2611) Based on the above discussion, this issue was opened in Aug 2019 and closed by @teoli2003 in Aug 2022. I don't believe the issue has been addressed. For example, looking at [radio](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio#additional_attributes), there are two additional attributes listed, but we really should have a unique section for `name` and `required`, as they both behave uniquely for radio buttons. `name`'s uniqueness is included in the text, but `required` is not. Also, [examples could be improved](https://github.com/mdn/content/issues/20342)
* [Update what attributes are supported by each input types](https://github.com/mdn/content/pull/17346) This (merged) pull request is a good start. There is a table of attributes with a column on what input types the attribute is supported. The page also contains a few details on each attribute, but it could go further. Continuing on the radio example, `required` and `name` are not hilited as being different for radio.
* [All HTML issues](https://github.com/mdn/content/labels/Content%3AHTML) and all  [mentions of attribute in HTML issues](https://github.com/mdn/content/issues?q=is%3Aopen+label%3AContent%3AHTML+attribute+is%3Aissue) Search result for all issues related to HTML, as most of them are related to HTML attributes.
* [Missing HTML attributes meta issue](https://github.com/mdn/content/issues/1712) In early 2021, Rachel Andrew created a list of all HTML attributes. This was closed until the [first item on this list](https://github.com/orgs/mdn/discussions/200) is resolved. The whole attribute discussion is circular, and needs to be resolved instead of just being discussed.

**Comment by teoli2003** [comment]
I agree that there is a problem to solve here, especially for input elements.

What is important, though, is not to have an _HTML/Attributes/<name>_ hierarchy but an _HTML/Element/<name>/Attributes/<name>_ hierarchy, like in BCD. (Except for the global attributes of course).

Because there is no guarantee that two attributes with the same name will have the same semantic on two different elements. (The _SVG/Attributes/<name>_ area of MDN is unmaintainable, incomplete – because it is difficult to improve it –, and difficult to read, because of the hierarchy problem).

**Comment by Elchi3** [comment]
This issue only contains a bunch of links to (closed) issues and no explanation.
Can you please describe what work we would be doing here in order for this to be considered an OWD project proposal?

**Comment by estelle** [comment]
> This issue only contains a bunch of links to (closed) issues and no explanation. Can you please describe what work we would be doing here in order for this to be considered an OWD project proposal?

Done, inline (edited the original post)

**Comment by Elchi3** [comment]
I'm closing this as not planned for the moment. We can always come back and make a plan about HTML attributes but there is no plan yet. If we want to reconsider this, let's have a discussion, an agreed plan, and a new OWD project proposal.
