### ISSUE TITLE
Project: HTTPArchive

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#118]
Participate in the HTTPArchive project

* [ ] Review Performance 2022 https://github.com/HTTPArchive/almanac.httparchive.org/issues/2890
* [ ] Review Accessibility 2022 https://github.com/HTTPArchive/almanac.httparchive.org/issues/2889
* [ ] Review Privacy 2022 https://github.com/HTTPArchive/almanac.httparchive.org/issues/2891
* [ ] Review CSS 2022 https://github.com/HTTPArchive/almanac.httparchive.org/issues/2879

Any other ones? Privacy? JS? APIS? Fonts? Markup? See https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aissue+is%3Aopen+2022+label%3A%222022+chapter%22

**Comment by Elchi3** [comment]
Thanks for filing this OWD project proposal!

I'm not familiar with the HTTPArchive project but the linked issues all have a publication date of September 26 ...
Can you elaborate a bit what our involvement should be (or has been) until then?

If there hasn't been any involvement from our side, I guess we should reconsider this project in the next year and close here for now.

**Comment by Elchi3** [comment]
Closing this. Deadline is too soon.
