### ISSUE TITLE
Project: remove `{{event}}` macro from MDN

### ISSUE THREAD

**Issue by queengooborg** [openwebdocs/project#122]
The `{{event}}` macro has become largely irrelevant as we have transitioned to a new events structure.  This project is all about removing the remaining calls to the macro.

As of creating this issue, for the main locale, we have 94 matches for `{{event` or `{{ event` across 42 files.  Translated content has far more, with 9879 matches across 1382 files.

**Comment by teoli2003** [comment]
\o/ We were at 800 on en-US only last year. So we did a lot of progress.

**Comment by queengooborg** [comment]
Oh wow, looks like this has pretty much entirely been taken care of now for the English locale -- the only file left will be removed in https://github.com/mdn/content/pull/18778!

**Comment by teoli2003** [comment]
Yes, @mfuji09 did an _amazing_ job on this removal work.

**Comment by Elchi3** [comment]
Closing this here. I think this is done and we are not planning to help with translations.
