### ISSUE TITLE
Link issue on https://opencollective.com/open-web-docs

### ISSUE THREAD

**Issue by tomayac** [openwebdocs/project#125]
The link points at https://github.com/openwebdoc instead of https://github.com/openwebdocs (plural).

![Screenshot 2022-09-05 at 15 35 33](https://user-images.githubusercontent.com/145676/188462375-c84104f6-6afe-4462-ae61-036f7a0c7621.png)

**Comment by Elchi3** [comment]
Thanks, I made it point to https://github.com/openwebdocs/project which seems most useful right now. (website coming soon).
