### ISSUE TITLE
[MDN] Improve Container Queries docs

### ISSUE THREAD

**Issue by schenney-chromium** [openwebdocs/project#127]
### Problem statement

There are currently no CSS Property pages for "container-name" or "container-type", nor a CSS At-Rules page for @container. They should be added now that the feature is in Safari, Chromium-based browsers and on the way in Firefox.

The general info page, https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries is a year old and needs sigificant updating.

### Proposed solutions

Create the appropriate new pages and re-work the existing general page to remove outdated references.

### Task list

Create:
- https://developer.mozilla.org/en-US/docs/Web/CSS/container-name
- https://developer.mozilla.org/en-US/docs/Web/CSS/container-type
- https://developer.mozilla.org/en-US/docs/Web/CSS/container
- https://developer.mozilla.org/en-US/docs/Web/CSS/@container

Update:
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries

### Priority assessment

- **Effort**: 
- **Dependencies**: 
- **Community enablement**: 
- **Momentum**: 
- **Enabling learners**: 
- **Enabling professionals**:
- **Underrepresented topics / Ethical web**: 
- **Operational necessities**:
- **Addressing needs of the web industry**:

**Comment by wbamberg** [comment]
See also https://github.com/mdn/content/issues/16862.

**Comment by dipikabh** [comment]
We can now use this issue to track the documentation work for container queries: https://github.com/mdn/content/issues/20987

**Comment by Elchi3** [comment]
This got finished :)
