### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by manekinekko** [openwebdocs/project#15]
Hey, I'd like to offer my help. Please let me know how can I contribute.

cc @robnyman @kypflug

**Comment by Elchi3** [comment]
Hey, thanks for offering help!

The current focus of the Open Web Docs collective is to help established documentation sites, such as MDN, and 
I can think of a few options for you to help out:
- Contribute to [MDN Web Docs](https://developer.mozilla.org/en-US/)
  - See the [GitHub repo](https://github.com/mdn/content) and the
  - [Getting Started guide](https://github.com/mdn/content#making-contributions)
  - Have a look at the [issue list](https://github.com/mdn/content/issues)
  - Let me know if there is any particular web platform documentation area or MDN bugfix you're interested in and I'll happily help you to get your first PR merged!
- Help spread the word about Open Web Docs, for example on [Twitter](https://twitter.com/OpenWebDocs).
- Donate to the collective to support [Open Web docs](https://opencollective.com/open-web-docs) Tech Writers financially.

Additionally, we'll host a Q&A session in February, subscribe to our [Twitter](https://twitter.com/OpenWebDocs) channel or to our [newsletter](https://newsletter.openwebdocs.org) for the exact date and time.

Cheers :)

**Comment by robnyman** [comment]
@manekinekko Wassim! Sorry for a late reply, it's been a few busy days lately. :-)

Everything @Elchi3 said are good ways to get started. Knowing you, I think for you to think about where your expertise could be reflected in docs on MDN would be really good. Also, if you can make the Q&A and spread the word about Open Web Docs, it would be greatly appreciated!

**Comment by manekinekko** [comment]
Thank you @robnyman @Elchi3 I appreciate your answers 👍

Here is [my first post on dev.to](https://dev.to/wassimchegham/introducing-open-web-docs-4g1m) about the announcement. I will do my best to join the Q&A _if the time allows it._

I am so excited about this initiative ❤️
