### ISSUE TITLE
OWD project: Replace XMLHttpRequest in examples with fetch()

### ISSUE THREAD

**Issue by wbamberg** [openwebdocs/project#156]
### Problem statement

Although we have for some time promoted fetch() and un-promoted XMLHttpRequest, we still have lots of examples that date from XMLHttpRequest times. We should if appropriate update them to use fetch().

### Task list

This would take an analysis phase, to figure out where we are using XHR and where we should replace it with fetch().

### Priority assessment

- **Effort**:  Medium
- **Dependencies**:  No
- **Community enablement**: Yes? (could get community help for this)
- **Momentum**: No
- **Enabling learners**: Yes
- **Enabling professionals**: Yes
- **Underrepresented topics / Ethical web**: No
- **Operational necessities**: No
- **Addressing needs of the web industry**: Yes

**Comment by Josh-Cena** [comment]
See also: https://github.com/openwebdocs/project/issues/156

**Comment by Elchi3** [comment]
> This would take an analysis phase, to figure out where we are using XHR and where we should replace it with fetch().

@teoli2003 can you do the analysis and post it here? Once we have this, I can label this project "ready".

**Comment by yarusome** [comment]
A further suggestion: During this project, could `await` and `try...catch` be used in place of `promise.then()` and `promise.catch()`? The lengthy chains easily produced by the latter two make codes far less legible.

**Comment by wbamberg** [comment]
I'm closing this as completed: https://github.com/mdn/imsc-examples/pull/14 is still open but (1) it's not in content and (2) it's approved.

I haven't checked through mentions of XHR in Firefox/Releases, but apart from that all places we refer to XHR across MDN should be updated. This doesn't mean we don't mention XHR at all of course, it's still a legitimate part of the web platform. But we promote fetch() instead, and try to make it so people are aware of fetch() as the defalt tool to reach for when making HTTP requests.
