### ISSUE TITLE
OWD BCD project: write unittests to cover 90% of internal code

### ISSUE THREAD

**Issue by queengooborg** [openwebdocs/project#162]
### Problem statement

BCD is home to numerous scripts that keep the project operating at its best.  However, only a few scripts have unittests written for them, and those that do are hardly touched.  

![screencapture-file-Users-queengooborg-Developer-Gooborg-browser-compat-data-coverage-lcov-report-index-html-2023-06-03-18_10_23](https://github.com/openwebdocs/project/assets/5179191/94cbf9d7-4704-46c8-959f-1b9357cf45d1)

We should work to improve unittest coverage of our scripts to make sure they're all working as intended.

### Task list

- [ ] 

### Priority assessment

- **Effort**: 
- **Dependencies**: 
- **Community enablement**: 
- **Momentum**: 
- **Enabling learners**: 
- **Enabling professionals**:
- **Underrepresented topics / Ethical web**: 
- **Operational necessities**:
- **Addressing needs of the web industry**:

**Comment by Elchi3** [comment]
Thanks for your proposal. We've improved some unit tests for critical code paths but we currently don't have the capacities to work on a project that improves BCD's unit tests further. Feel free to refile this on the BCD repo in case other BCD contributors want to pick some of the proposed work here.
