### ISSUE TITLE
OWD project: Fix errors in BCD for API, CSS and JS going back to at least 2016

### ISSUE THREAD

**Issue by queengooborg** [openwebdocs/project#167]
### Problem statement

Following the completion of https://github.com/openwebdocs/project/issues/85, one avenue to pursue would be to push the threshold further back and fix errors in BCD for API, CSS and JavaScript going back even further, to 2016 (specific year is flexible).

### Task list

- [ ] 

### Priority assessment

- **Effort**: 
- **Dependencies**: 
- **Community enablement**: 
- **Momentum**: 
- **Enabling learners**: 
- **Enabling professionals**:
- **Underrepresented topics / Ethical web**: 
- **Operational necessities**:
- **Addressing needs of the web industry**:

**Comment by Elchi3** [comment]
Can you get data about how large the discrepancies are? Something like:

2020+: 100% accuracy
2019+: 98% accuracy
2018+: 92% accuracy

**Comment by queengooborg** [comment]
I'll see if I can whip up some numbers for each year!  I don't have the infrastructure in place to get percentages, would line diff counts be alright?

**Comment by Elchi3** [comment]
line diff counts would be alright, yes. Just to get a feeling how much work it is the further we go into the past

**Comment by queengooborg** [comment]
Here's the statistics as requested!

- 2020+: 1 file changed, 240 insertions(+), 142 deletions(-) (This is RTCStatsReport)
- 2019+: 26 files changed, 498 insertions(+), 400 deletions(-)
- 2018+: 85 files changed, 789 insertions(+), 594 deletions(-)
- 2017+: 127 files changed, 925 insertions(+), 727 deletions(-)
- 2016+: 173 files changed, 1232 insertions(+), 1031 deletions(-)
- 2015+: 207 files changed, 1426 insertions(+), 1223 deletions(-)
- All Selenium-accessible browser versions: 236 files changed, 1470 insertions(+), 1260 deletions(-)

**Comment by Elchi3** [comment]
I'm going to close this as not planned (for now). We might want to have compat data going back further than 2020 in some situations (see https://github.com/openwebdocs/mdn-bcd-collector/pull/1033#issuecomment-1892767630), but overall, the number of issues we get on BCD about compat data that is older than 2020 is quite low I think. It's much more important to get the latest information for new browser releases right and it is also more important that we increase the coverage of the OWD bcd-collector.

The statistics you researched are quite interesting to see how much discrepancies there are between BCD and the collector. I reckon the collector tests more than 2000 files in BCD, so it seems that 10% of historic data (if we were to chose all Selenium-accessible browsers) have discrepancies with the collector. Not all of these might be problems in BCD! If going back quite far, some test techniques in the collector will stop to work (like CSS @supports wasn't in browsers from the start), so then this project will be a lot about fixing the collector for older browsers.

If the importance of fixing older compat data changes, we can always reopen this project, but it also not exactly easy to research the older compat data for the reasons outlined. Thanks for proposing this, though. It lead to some interesting insights in BCD's data quality.
