### ISSUE TITLE
OWD project: Resolve/close old content and/or BCD issues

### ISSUE THREAD

**Issue by queengooborg** [openwebdocs/project#172]
### Problem statement

An ambitious project idea has come to mind that I wish to propose.  At the time of writing, mdn/content has 621 open issues, and BCD has 689.  Out of these issues, hundreds have been opened before 2022 (145 for content, 251 for BCD).  It would be great to work through these issues and resolve or close them.

To keep things manageable in this pass, I propose that we focus on issues opened in 2021 or earlier.

### Proposed solutions

To reduce our issue count, I propose that we triage these old issues and close irrelevant ones quickly, and work to resolve the other ones.  Often times, we'll stumble across issues that are for removed content, are self-promotion, or don't align with our goals -- those issues can simply be closed.  Others may require significant work updating a page or BCD, and may require a topic expert -- we should ping those experts as soon as possible.

### Task list

- Start by searching for `is:issue is:open created:<2022-01-01` in mdn/content or mdn/browser-compat-data to filter for open issues created before Jan 1, 2022.  For each issue...
  - Close if...
    - It is for a document that has been deleted
    - It is self-promotion
    - It pertains to Internet Explorer, Netscape or another irrelevant browser
    - It is otherwise irrelevant to MDN
  - If the issue seems like it is resolved, but you aren't sure...
    - ...post a comment asking if it can be closed.
  - If the issue is for a different repository...
    - ...move it to the appropriate repo or ping someone with permissions to do so.
  - If the issue requires a topic expert...
    - ...ping the topic experts.
  - If the issue can be resolved...
    - ...submit a pull request to resolve it, or...
    - ...reach out to your fellow writers for advice on how to resolve it.

### Priority assessment

- **Effort**: Large.  Estimating two quarters (six months).
- **Dependencies**: N/A
- **Community enablement**: This is mostly a maintainer cleanup project, but we can get the community involved with resolvable issues, especially if they're a good first issue.
- **Momentum**: This will help show that OWD cares greatly about improving MDN Web Docs.
- **Enabling learners**: n/a
- **Enabling professionals**: n/a
- **Underrepresented topics / Ethical web**: n/a
- **Operational necessities**:
- **Addressing needs of the web industry**: Web developers open issues when they notice something doesn't seem right with the docs or data; we will be addressing their direct needs by working through the log of open issues.

### More information

Open Web Docs (OWD) is a non-profit collective funded by corporate and individual donations.

In order for this project to happen, please consider donating to OWD on https://opencollective.com/open-web-docs.
For more information on sponsorship and membership tiers, see https://openwebdocs.org/membership/

More information is available at https://openwebdocs.org/.
For questions, please reach out to [florian@openwebdocs.org](mailto:florian@openwebdocs.org).

**Comment by Elchi3** [comment]
Thanks Vinyl, it is indeed an ambitious project and unfortunately we don't have the bandwidth to do this currently. Maybe in some future there could be at a sprint/hackathon and we try to triage and get into a lot of the older BCD and content issues but right now I don't see us having the capacities beyond the help we are already providing on a daily basis to these projects.
