### ISSUE TITLE
CSS Module: Fonts

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#176]
Page: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_fonts

 - [x] brief (5-paragraph approx) description
 - [ ] demonstration example
 - [x] properties
 - [x] descriptors
 - [x] data types
 - [x] associated properties
 - [ ] glossary terms
 - [x] https://drafts.csswg.org/css-fonts/

**Comment by RTLY059** [comment]
> 



> Страница: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_fonts
> 
> * [x] краткое (примерно 5 абзацев) описание
> * [ ] демонстрационный пример
> * [x] характеристики
> * [x] дескрипторы
> * [x] типы данных
> * [x] связанные свойства
> * [ ] глоссарий терминов
> * [x]  [https://drafts.csswg.org/css-шрифты/](https://drafts.csswg.org/css-fonts/)
