### ISSUE TITLE
Anchor positioning: css module

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#178]

**Comment by estelle** [comment]
Tested chrome, edge, firefox and safari. No implementations yet. No need to document.

**Comment by estelle** [comment]
This is being addressed in the following PRs:

https://github.com/mdn/content/pull/33058
https://github.com/mdn/content/pull/33467
https://github.com/mdn/content/pull/33493
https://github.com/mdn/content/pull/33511
https://github.com/mdn/content/pull/33609

**Comment by Elchi3** [comment]
Thanks for providing reviews for all of these, Estelle! 💯

**Comment by Elchi3** [comment]
This looks done to me.
