### ISSUE TITLE
Amplifying messages via web.dev/blog

### ISSUE THREAD

**Issue by kaycebasques** [openwebdocs/project#20]
Just sending off a quick message before I forget: we'd be happy to post announcements from time-to-time. Maybe not everything, but key posts. E.g. after 6-months or something maybe you do a roundup of all the work you've done so far, and then the CTA is "BTW plz donate"

We'll have to work out details but I just want to put it on your radar that web.dev/blog is available to spread the good word

**Comment by Elchi3** [comment]
Hey! That's awesome! I started doing monthly roundups, see January 2021 here: https://opencollective.com/open-web-docs/updates/open-web-docs-worklog-january-2021-edition. I'm happy to post a 6 month version of it to web.dev/blog! 🎉 
Thanks so much for reaching out!

**Comment by kaycebasques** [comment]
Sounds good. I'll close this to avoid cluttering up your issues.
