### ISSUE TITLE
Amend the Charter doc to clarify our position on free/paid countent?

### ISSUE THREAD

**Issue by torgo** [openwebdocs/project#38]
Do we need a policy statement from OWD that OWD will only put effort / energy into features & content that is fully free to consume?

**Comment by wbamberg** [comment]
Yes, I think we should (both only work on free content and have that explicitly in the charter). I think we should connect this with making web documentation available to as many people as possible. But I'm not sure how we should integrate that into the current wording of the charter.

**Comment by Elchi3** [comment]
Yes.

Would it be sufficient enough to add some bits to the last paragraph? Like so:

> Open Web Docs invests in and protects <ins>free</ins> documentation for the open web platform. We provide incentives and a platform for other related organizations to get involved in this work. We ensure developers have the best information available <ins>for free</ins> to make technology and design decisions and implement on the web platform.

Or do we think this needs its own core value?
