### ISSUE TITLE
Project: Branding: OWD Website

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#54]
Websites are the center of an organization's online presence. The site serves as the organization's online hub of information.  openwebdocs.org is where visitors should go for information about our projects, where search engines direct visitors, including volunteers and potential contributors, where email announcements should lead to, and a hub for links in social media posts. Instead, we have MDN, a GitHub repo, Google Docs, and a page (and our current redirect) https://opencollective.com/open-web-docs

Creating an OWD website will have the following benefits:
1. Makes us appear legitimate
1. Informs visitors how to reach us
1. Informs potential volunteers how to get involved
1. Converts donors: Convinces (and enables) potential financial donors to contribute
1. Tells our story
1. Expands our reach
1. Drives new Interest
1. Provides for a positive impression
1. Provides a central repository to links to our projects, issues, newsletters, etc.

In general, the website will help boost all our efforts

**Comment by Elchi3** [comment]
Actually, it is https://github.com/openwebdocs/owd-website now. But I think we can close here. Please file issues in the website repo. Will ask in today's call if there is anything left to do before launching.
