### ISSUE TITLE
OWD Q4 projects

### ISSUE THREAD

**Issue by Elchi3** [openwebdocs/project#55]
We met yesterday (September 8th, 2021) to go through current OWD project proposals and ideas.
This issue summarizes them so we can discuss which projects to take on in Q4 2021 (the months October, November, December). For reference, the Q3 issue is https://github.com/openwebdocs/project/issues/42.

# Continued projects
These projects have been started, likely won't get done completely in Q3, and it makes sense to continue them in Q4.
- [Markdown conversation for more of MDN](https://github.com/openwebdocs/project/issues/25). Driver: @wbamberg
  - 70% will be done after the Web/API conversion in Q3
  - Hamish started work on Glossary/ and Learn/. Help him to finish.
  - Finish the rest: HTML, SVG, WebExtensions, MDN/MDN, WebAssembly, and  "tiny areas".
  - Tricky one is HTML/ because of HTML :) (and live samples)
- [Documenting HTTP/3](https://github.com/openwebdocs/project/issues/43). Driver: @teoli2003 
  - Follow-up from documenting HTTP/2 in Q3 
- [ARIA roles reference docs](https://github.com/mdn/content/blob/main/rfcs/aria-roles.md). Driver: @estelle 
 
# Potential new projects
These are projects that have been discussed before or are new proposals. We will [assess](https://github.com/openwebdocs/project/blob/main/steering-committee/prioritization-criteria.md) them and a stack ranking exercise will determine their importance (every SC member is encouraged to propose projects and to participate in stack ranking). Preparation drivers are people who make sure we have all the information to get started with the project if it gets prioritized by the group.

- [Fix how MDN distributes Polyfills](https://github.com/openwebdocs/project/issues/27) Preparation driver: @teoli2003 
- [WebView information on MDN](https://github.com/mdn/content/blob/main/rfcs/webview-information.md). Preparation driver: ???
- [Modernizing the Learning Area JavaScript modules](https://github.com/mdn/content/blob/main/rfcs/modernize-learn-js.md). Preparation driver: ???
- [Use webref as the source for CSS formal syntax, instead of mdn/data](https://github.com/openwebdocs/project/issues/44). Preparation driver: @wbamberg 
Ideas
- [Documenting WebDriver](https://github.com/mdn/content/issues/4721). Preparation driver: ??? (Reeza offered help when it comes to EdgeDriver)
- [Web Testing strategies](https://github.com/mdn/content/issues/3917). Preparation driver: ???
- [Fixing MDN page titles](https://github.com/mdn/content/discussions/5121). Preparation driver: ???
- [Updating DOM guides (and completing its reference)](https://github.com/openwebdocs/project/issues/50). Preparation driver: @teoli2003 
- [Documenting events and representing them in BCD](https://github.com/openwebdocs/project/issues/61). Preparation driver: @foolip / @Elchi3
- [Documenting Performance APIs](https://github.com/openwebdocs/project/issues/62). Preparation driver: ??? 
- [Improving Privacy Docs](https://github.com/openwebdocs/project/issues/60). Preparation driver: ???
- [WebXR guides](https://github.com/mdn/content/issues/7276). Preparation driver: @dominiccooney / @Elchi3.
- [ARIA attributes](https://github.com/openwebdocs/project/issues/65). Preparation driver: @estelle
- [100% complete BCD API data (no true/null values)](https://github.com/openwebdocs/project/issues/66). Preparation driver: @foolip.
- [Sidebars for content architecture refresh](https://github.com/openwebdocs/project/issues/67). Preparation driver: @ddbeck / Mozilla MDN team.
- [OWD project: clean up BCD data guidelines](https://github.com/openwebdocs/project/issues/69). Preparation driver: @ddbeck 
# Mozilla MDN projects

Mozilla shared these MDN projects for Q4 and we might want to collaborate with them.

- Content reorg (Ruth)
- Documenting WebGPU (Ruth & Joe Medley)
- Demos (Ruth)
- Project Synth / contribution docs (Ruth)

**Comment by foolip** [comment]
> Documenting events and representing them in BCD. (needs issue!) Preparation driver: @foolip

There's already https://github.com/mdn/browser-compat-data/issues/7545 and https://github.com/mdn/browser-compat-data/issues/12290, are issues in mdn/content and here also needed?

> Content reorg (Ruth)

@Rumyra do you have details on this you could share? In particular, if API docs will be reorganized, I'd be interested to see what the proposed structure is.

**Comment by foolip** [comment]
> every SC member is encouraged to propose projects and to participate in stack ranking

@Elchi3 how should we go about this? Simply by posting an ordered list in this issue?

**Comment by Elchi3** [comment]
> There's already [mdn/browser-compat-data#7545](https://github.com/mdn/browser-compat-data/issues/7545) and [mdn/browser-compat-data#12290](https://github.com/mdn/browser-compat-data/issues/12290), are issues in mdn/content and here also needed?

An OWD issue here that summarizes what should be done on both MDN and BCD for this whole topic would be appreciated, yes.

> @Elchi3 how should we go about this? Simply by posting an ordered list in this issue?

Given the list of projects we want to consider for stack ranking might not be complete yet (please propose projects until September 29 still!!), please don't post an ordered list yet. Last time, I took ordered lists from people in the call but I'm also happy to receive them here or async elsewhere on or around September 29. (aside: I think it is better if people think for themselves and aren't influenced by other people's ordered lists).

**Comment by foolip** [comment]
I'd like to "propose" a project to group compat tables in a way that puts deprecated stuff at the end. I know that either @Elchi3 or @ddbeck has talked about doing this already, but I don't remember who :) Is there an issue for this somewhere already?

**Comment by ddbeck** [comment]
@foolip I talked about talking to Daryl (the designer at Mozilla) about including this in her site design efforts coming later in the year. Though I expect there's a bit of work that could be more formally part of BCD to support that (e.g., defining a canonical pretty sort for features). I haven't opened an issue yet and Daryl's on vacation until later in the month, so I was on hold for that stuff as I saw it

**Comment by dominiccooney** [comment]
I have sketched some project proposals in #57, #58, #59 and #60.

**Comment by yoavweiss** [comment]
Hey folks! @mmocny and others put together a list of documentation issues for the various performance APIs in https://github.com/openwebdocs/project/issues/62

Would be great if y'all can put that on your lists! :)

**Comment by Elchi3** [comment]
@dominiccooney 

> I have sketched some project proposals in #57, #58, #59 and #60.

Thanks! I've commented these and added the Privacy docs project to the list of OWD projects to consider for Q4 for. Input needed on the other issues.

@yoavweiss 

> Hey folks! @mmocny and others put together a list of documentation issues for the various performance APIs in #62
> 
> Would be great if y'all can put that on your lists! :)

Thanks much! I've added the Performance API project proposal to the list of OWD projects to consider for Q4.

**Comment by foolip** [comment]
I filed the events proposal as https://github.com/openwebdocs/project/issues/61.

**Comment by foolip** [comment]
I've also filed https://github.com/openwebdocs/project/issues/66, which is my attempt to rally more support around getting BCD's API data to 100% this year.

**Comment by Elchi3** [comment]
Thanks @foolip, both look well defined to me, so I added them.

**Comment by ddbeck** [comment]
I've filed https://github.com/openwebdocs/project/issues/67 to regularize Will's ongoing contributions to menace of sidebars.

**Comment by ddbeck** [comment]
OK, one more last-minute suggestion, if it's not too late: https://github.com/openwebdocs/project/issues/69

**Comment by Elchi3** [comment]
The Open Web Docs Steering Committee took part in an open prioritization process. 14 members of the SC handed in their ranked list and I've calculated an overall rank from there. The data is available here: https://docs.google.com/spreadsheets/d/1zuaBQ__4_2-s2LiiK9A4-XaQUIR0ucN7O1OYWQ1TsfE/edit#gid=0 (please let me know if there are flaws)

The overall rank is:

1. ARIA attributes
2. Updating DOM guides (and completing its reference)
3. Modernizing the Learning Area JavaScript modules
4. Documenting events and representing them in BCD
5. Use webref as the source for CSS formal syntax, instead of mdn/data
6. 100% complete BCD API data (no true/null values)
7. Fix how MDN distributes Polyfills
8. WebView information on MDN
9. Fixing MDN page titles
10. Documenting Performance APIs
11. Improving Privacy Docs
12. OWD project: clean up BCD data guidelines
13. WebXR guides
14. Web Testing strategies
15. Sidebars for content architecture refresh
16. Documenting WebDriver

Given there are a few continued projects from Q3, 2022 planning, and end-of-year holidays, the initial reaction from the team is that we would like to try to make progress on projects 1-5 at most. (we are a team of 4 given our current budget)

If anyone plans to take on any of the other projects (Mozilla signaled work is going to happen on project 15), we're happy to help but we will most likely not have the time to drive it.

Thanks to everyone who submitted proposals. All suggested projects are great and needed. I'm open to feedback on this process and I'm happy to do this again for Q1 where projects that didn't make it this time can be nominated again. Cheers!
