### ISSUE TITLE
"Better" Browser Compatibility Decision Support

### ISSUE THREAD

**Issue by dominiccooney** [openwebdocs/project#57]
Browser compatibility data in MDN is usually pretty good but could be better. It is necessary to consult caniuse.com which has links to other sites that describe bugs, edge cases and work-arounds. 

Here are some observations of some good points of caniuse. These observations aren't intended as "make MDN like this" or "make BCD like this" but as a starting point to investigate what decisions people use MDN compatibility tables for and how MDN could inform those decisions better:

While there are notes in BCD, examining the content highlights the nature is a bit different. MDN may even have similar content but it is not in context.

The presentation is different, on MDN you have to expand notes per property, per browser; on caniuse the information is in hovercards and you can see a list of "known issues" in one place. There is more consistency between browsers (for example, look at caniuse.com/flexbox notes and see that note 1 applies to 5 browsers from 3 vendors.) The caniuse presentation shows browsers aligned by date, share, current version, etc.; this might be easier to parse for people who have a certain support policy like "two latest versions" or "anything in the past two years" or "x% share" etc.

The granularity of the data are also different; for example, caniuse.com has one entry per browser for "Pointer Events" but on MDN you have to parse a table of 17 rows per browser.

caniuse.com has less friction for reporting data problems than BCD.

The MDN compatibility table may suffer from the simple problem of being at the bottom of the page. caniuse has big #s to encourage deep linking, etc.

**Comment by Elchi3** [comment]
I'm tagging @ddbeck here who might know more about MDN compat table redesign plans. I'm not entirely sure how OWD could help immediately (in Q4), but if Daniel has pointers into what the plan is, then we're happy to help with the efforts or helping with making a plan for better compat tables.

The feedback you've collected is useful. It would also be great to have place to record feedback that informs compat table redesign. Daniel, is there such a place in the open?

**Comment by dominiccooney** [comment]
It sounds like this work is already happening somewhere inside Mozilla, so let me close this issue. If that's wrong, feel free to reopen it.
