### ISSUE TITLE
Faster search to MDN content

### ISSUE THREAD

**Issue by dominiccooney** [openwebdocs/project#58]
When web developers are seeking documentation from MDN, the search results often include another site with apparently better SEO but less useful documentation. Developer have to repeat searches to exclude that site or mention MDN.

Something to take the friction out of searching for content on MDN when you don't have MDN open in front of you would help developers get the content they need. SEO, search providers could help.

**Comment by Elchi3** [comment]
Thanks for your proposal! Like improving performance, accessibility, or security, improving searchability ("seo") is an ongoing effort. Do you propose we make an audit to figure out what work to do here exactly? I think as is this proposal is too abstract to be actionable for Q4.

**Comment by dominiccooney** [comment]
Agree that this isn't specific enough to act on for Q4. Let me close this for now.
