### ISSUE TITLE
Remove obsolete HTML

### ISSUE THREAD

**Issue by wbamberg** [openwebdocs/project#63]
Our HTML documentation contains lots of pages for elements and attributes that have been obsolete for a long time. For example:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/applet
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/basefont
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bgsound
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/big
etc etc
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table#deprecated_attributes

Although many of them are still supported in browsers, I don't see any good reason for us to document them on MDN any more. As it is they just get in the way of people looking for things that they should use.

We could list them in a single page under HTML/Obsolete (say), or just delete them (my preference).

**Comment by teoli2003** [comment]
I think having an "Obsolete" page with a section for each of them, as well as some redirect in place would be good.

For deprecated attributes, another way would be to group them in an element page and hide them with a `<summary>`/`<details>`

**Comment by tomayac** [comment]
Things like `bgsound` definitely are a big part of Web history, so deleting seems overzealous to me. Maybe add a _super scary_ new banner on top that says "Obsolete", apart from the existing "Deprecated" banner.

**Comment by Elchi3** [comment]
I think this issue should be filed at (or be a discussion on) mdn/content :)

**Comment by wbamberg** [comment]
OK, I can't apparently transfer to the MDN org so I will just close this. I guess I just got annoyed at all the obsolete stuff in our HTML docs :(.

> Things like bgsound definitely are a big part of Web history, so deleting seems overzealous to me. Maybe add a super scary new banner on top that says "Obsolete", apart from the existing "Deprecated" banner.

I'm not sure that something being part of Web history means it should be documented on MDN. IMO we should address the needs of developers today.

I'm also not sure about super scary banners. We already have lots of these. The issue isn't that people won't understand that they shouldn't use long-deprecated features, it's that these docs are just noise.
