### ISSUE TITLE
OWD Project: ARIA States and Properties

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#65]
We should have complete documentation for the [ARIA spec](https://w3c.github.io/aria/) within MDN.

ARIA roles is currently [in development](https://github.com/estelle/content/tree/ariaroles/files/en-us/web/accessibility/aria/roles).

There are 50+ aria states and properties needing to be documented.

1. Index page at /en-US/docs/Web/accessibility/aria/attributes
   * Four groupings: widget, live region, drag-and-drop, and relationship attributes
   * quick links to all the attributes based on group (name only)
   * List of all the attributes in alphabetical order with summary
   * include link to the role attribute, which doesn't start with aria-*
2. 53 New documents: one for each of the widget, live region, drag-and-drop, and relationship attributes

**Comment by foolip** [comment]
I'm not sure I understand what the 50+ things are in the spec. Is it the HTML attributes and their values that should be documented here, such as `aria-labelledby="label"`? https://w3c.github.io/aria/#statevsprop says:
> In this document, states and properties are both treated as aria-prefixed markup attributes. However, they are maintained conceptually distinct to clarify subtle differences in their meaning.

If states and properties are only subtly different to the developer-visible attributes that are used to control states and properties, should the documentation rather be of the attributes?

**Comment by estelle** [comment]
Yes. States and properties is the documentation of the aria-* attributes -- 50+ of them.

**Comment by estelle** [comment]
Squeeee!
