### ISSUE TITLE
OWD project: plan sidebars for content architecture refresh

### ISSUE THREAD

**Issue by ddbeck** [openwebdocs/project#67]
**Summary**: Sidebars are difficult for readers to navigate, but authoring sidebars is sufficiently difficult that making improvements to sidebar navigation is not currently practical. This is a step forward to fixing the latter, so we can fix the former.

Daryl (and others) are working on a visual refresh of MDN. Some of the proposed changes have impacts on information and content architecture. The content and arrangement of MDN’s sidebars are the clearest manifestation of these changes. To minimize unpleasant surprises, there ought to be a specific person representing authors in this process.

@wbamberg has already provided a lot of input in this area, so I think it makes sense that he would be the person to continue this work, but that's not an actual requirement (though it'd be nice to have a single owner, to make definitive judgement calls).

Tasks:

(these are rough tasks—to give a sense of the flavor and size of the work; a lot of this is going to be a consequence of design decisions, which aren't final yet)

- Document requirements for new sidebar structures to meet needs of refresh and authors
- Propose (interim? v1?) sidebar structure and seek feedback from designer, devs, and authors
- Write new static sidebar contents (e.g., write YAML files with actual structures) OR write specifications for new sidebar macro behavior

Stuff that’s not in scope:
- Sidebar implementation (e.g., writing code that generates sidebars)
- General content modeling work (we should do this at some point, there’s more discussions to be done in this area for it to be a coherent project—not ready for execution yet)

**Comment by queengooborg** [comment]
@Rumyra @fiji-flo How does this sound to you guys?

**Comment by Elchi3** [comment]
Thanks for filing this OWD project proposal!

I think we (mostly Will) can provide a draft plan for better sidebars on MDN. However, I think it only makes sense to work on such a plan if we have set up a collaboration with yari engineering to plan and ultimately implement new sidebars together. (cf. when we had a collab for markdown conversion).

Marking this as not ready / on hold for now until there are capacities for such a collaboration.

**Comment by teoli2003** [comment]
Revamp IA and implementation of sidebars would be a great fit for 2023, if Mozilla Writers (cc/ @Rumyra) and Mozilla Devs (cc/ @caugner) could secure resources on their side. (This OWD project would be a part of it, then)
