### ISSUE TITLE
OWD project: clean up BCD data guidelines

### ISSUE THREAD

**Issue by ddbeck** [openwebdocs/project#69]
**Summary**: To maintain the high quality of BCD data (which appears in compat tables and caniuse), we have conventions for recording certain data. Some of those conventions have been recently established, but were never written down, leading to a risk that that data will not be maintained properly. This proposal addresses that risk.

Recent efforts have caused BCD's data guidelines to slip out of sync with our actual practices. I'd like to propose a (hopefully small) effort to bring the data guidelines back in sync.

Some of these tasks have been nominally claimed by people who participated in them (e.g., sideshowbarker for spec_urls and foolip for globals). Perhaps they still want to work on them and might benefit from having a designated reviewer, or perhaps they'd like to hand off the task to some else.

I'd also be willing to be a reviewer, to support any or all of this work.

Tasks:

- [ ] Write (or review) a data guideline for how to choose a spec URL (e.g., which spec and URL fragment) (i.e., document the completed spec URL work
- [x] Write (or review) a data guideline for how to record globals (e.g., when to put an API in `__globals`) (i.e., document https://github.com/mdn/browser-compat-data/pull/11518)
- [x] Improve navigation of data guidelines (e.g., add more headings to group related guidelines and put the guidelines into some sort of meaningful order)

**Comment by Elchi3** [comment]
> Write (or review) a data guideline for how to choose a spec URL (e.g., which spec and URL fragment) (i.e., document the completed spec URL work

This got done?

**Comment by queengooborg** [comment]
I forgot that the spec URL documentation was a part of this -- let's split it off into its own project as it seems to be more like guideline "addition" instead of "cleanup"!  (Also because I don't feel that I know enough about spec URLs to write up a guideline for them... ;P)
