### ISSUE TITLE
Project: ARIA widget roles

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#75]
All the roles were documented in Q3 2021 with the exception of the widget roles.
This project would make the ARIA roles section of the MDN complete.
Roles to edit include:

Full documentation for:
 *  [x] scrollbar - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/scrollbar_role
 *   [x] searchbox https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/searchbox_role
 *   [X]  separator (when focusable) https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/separator_role
 *   [x]  slider https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/slider_role
*  [x] spinbutton https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/spinbutton_role
*    [x]  switch https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/switch_role
*    [x] tab https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role
*    [x] tabpanel https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tabpanel_role
*    [x] treeitem https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/treeitem_role
*    [x]  combobox https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/combobox_role
*    [x] menu https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role
*    [x] menubar https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menubar_role
*    [x]  tablist https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tablist_role
*    [x]  tree - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tree_role
*    [x]  treegrid https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/treegrid_role

Documentation for some of these exist. Others don't. But all need improvement.

Brief documentation needed for:
*    [x]  button https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role
*    [x] checkbox https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/checkbox_role
*    [x] gridcell https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/gridcell_role
*    [x] link https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/link_role
*    [x] menuitem https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menuitem_role
*    [x] menuitemcheckbox https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menuitemcheckbox_role
*    [x] menuitemradio https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menuitemradio_role
*    [x] option https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/option_role
*    [x] progressbar https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role
*    [x] radio https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/radio_role
*    [x] textbox https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/textbox_role
*    [x] grid https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/grid_role
*    [x] listbox https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role
*    [x] radiogroup https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/radiogroup_role

The reason the latter section needs brief pages is that the roles exist, but should not be used. So, we need to include them for completeness, but we don't need lots of details, just an explanation of existence and purpose, and a "do not use" warning.

**Comment by nschonni** [comment]
Might be some content in https://github.com/w3c/aria-practices that would help fill in the gaps or be referenced

**Comment by estelle** [comment]
Done!
