### ISSUE TITLE
OWD project proposal: regularize feature namespaces for CSS, HTML, HTTP, and JavaScript

### ISSUE THREAD

**Issue by ddbeck** [openwebdocs/project#80]
### Summary

Some browser compat data is poorly structured, negatively impacting data consistency, MDN page appearance, and other consumers (e.g., caniuse, VS Code). A relatively small number of changes to BCD and MDN content could eliminate these inconsistencies. Fixing this would involve:

- Moving data in BCD
- Updating pages to use the moved data
- Exploring options for the remaining parts not directly specified (i.e., SVG and webextensions)

### Background

Historically, structuring BCD was rather loose. This means some unusual cases exist, which are difficult to communicate to consumers, leave much to be desired in terms of rendering on MDN, and may have more widespread issues (e.g., in caniuse or VS Code). It has also prevented a stronger position on semantic versioning for BCD itself.

See https://github.com/mdn/browser-compat-data/issues/13804 for more details.

### Prioritization criteria

- Effort
  - Relatively small, as such things go. I imagine the core part (CSS, HTML, HTTP, and JavaScript) could be completed within a couple of weeks, with a dedicated effort by a writer.
  - The more speculative part is unknown. There's probably a day or two of analysis to be done; completion effort unknown.
- Dependencies
  - None of note.
- Community enablement
  - Not a large effort. It's unlikely to be shared effectively, or lead to more contributions (as this is cleaning up after contributors).
- Momentum
  - This is a new effort, though BCD has substantial reliance factors.
- Enabling learners
  - Not really applicable. Learners are generally unconcerned with compat issues; they need to support _their_ browser, not all browsers.
- Enabling professionals
  - Significant. Developers need reliable information on which browsers support various APIs, CSS properties, etc.
- Underrepresented topics / ethical web
  - Not applicable.
- Operational necessities
  - Not applicable.
- Addressing needs of the Web industry
  - BCD data is widely used on MDN, caniuse, VS Code, and elsewhere. Far reaching in this area.

**Comment by queengooborg** [comment]
This project has now been completed!
