### ISSUE TITLE
OWD project: Generate "experimental" banners from BCD

### ISSUE THREAD

**Issue by wbamberg** [openwebdocs/project#81]
Currently we store information about whether a feature is experimental in two different places:

* in the page itself, as a call to the {{SeeCompatTable}} macro, which adds a banner to the page
* in BCD, as a status flag

We do a pretty good job of maintaining the BCD version, much less well of the version in the page, so they often get out of sync and we get people asking why we are warning people about perfectly good APIs (see e.g. https://github.com/mdn/content/pull/9941, https://github.com/mdn/content/pull/11741, https://github.com/mdn/content/pull/10220, https://github.com/mdn/content/pull/10706, https://github.com/mdn/content/pull/12506, etc etc).

We should display "experimental" banners based on the data in BCD, just as we now display spec tables based on BCD data.

## What's involved?

* updating Yari so it displays an "experimental" banner based on BCD
* for pages that don't have BCD (mostly, API overview pages), add front matter to represent experimentalness
* remove the `{{SeeCompatTable}}` macro

### Immediate benefits

* more reliable pages
* easier to contribute and maintain MDN, as there's only one place to maintain this

### Long-term/strategic benefits

This is in line with our general desire to build MDN content from data, where that's appropriate. We should implement this with an eye to doing something similar for other MDN banners, like "deprecated", "available in workers", "requires a secure context", "requires permissions" etc. All these things should be amenable to maintaining as data and rendering in Yari, rather than being part of unstructured prose content.

### Effort

Medium. Need to:

* update Yari to add the banners based on BCD (small)
* update ~960 pages that currently use SeeCompatTable (small)
* design and implement a solution for pages that don't have BCD (small-medium)

### Dependencies

Needs a little Yari work.

### Community enablement

Make it easier to write MDN docs by only having one place to add the data.

### Momentum

n/a

### Enabling learners

More reliable docs benefit all users.

### Enabling professionals

More reliable docs benefit all users.

### Underrepresented topics / ethical web

n/a

### Operational necessities

n/a

### Addressing needs of the Web industry

n/a

**Comment by OnkarRuikar** [comment]
What about inline badges? `{{Deprecated_Inline}}`, `{{Experimental_Inline}}`, and `{{non-standard_inline}}`. e.g. https://developer.mozilla.org/en-US/docs/Web/API/Window They also need manual updates.

Can we have a macro that we can put in front of all props and method listings? Like:
```
- vrdisplayactivate {{InlineBadges{'window.vrdisplayactivate', 'readonly')}}
```
Which will yield following based on BCD:
> - vrdisplayactivate 🗑⚠🧪

Second onwards parameters could be extra badges, like readonly, that we may add in future. This will also put badges in same order everywhere. Right now there is no particular order in which the inline badges are displayed.

***
The deprecated etc. info is also stored in page tags.

**Comment by wbamberg** [comment]
I wouldn't really want to have macros after every item, when almost always they have no output. So much visual noise in the source and extra typing.

In some far-off future it would be nice if we could generate these kinds of lists of methods - for example if we can represent as data the fact that an interface has a particular set of methods (which already exists in things like the IDL), then we could generate the method listing, and automate these badges, as well as things like consistent typography and alphabetization.

**Comment by wbamberg** [comment]
Or for a less sci-fi place to be, if:

- we have a page type such as, say, "web-api-interface" (like [`Request`](https://developer.mozilla.org/en-US/docs/Web/API/Request))
- and we know that pages of this type might include a section "Methods"
- and we know that "Methods" there is a `<dl>` where the `<dt>` elements are links

...then perhaps Yari could peek at the front matter for those linked pages, and add the badges automatically.

**Comment by jensimmons** [comment]
I would love to see this. I would also recommend thinking carefully about the wording of the banner, so it conveys something that means "hey, this isn't in every browser yet, you should think through what to do and use progressive enhancement" instead of "this is dangerous, it's too early to think about using this technology, you should wait until it ships in all browsers".

**Comment by OnkarRuikar** [comment]
At the moment we are using a temporary solution to automatically update the banners and inline badges as per the latest BCD.
A script runs automatically after every [BCD release](https://github.com/mdn/browser-compat-data/releases) and updates the docs. The script is not part of the yari; once stable it may become part of the [mdn/content automation](https://github.com/mdn/content/blob/main/.github/workflows/markdown-lint-fix.yml).
This is not ideal but [it has been keeping the things up to date](https://github.com/mdn/content/pulls?q=is%3Apr+author%3Aonkarruikar+sort%3Aupdated-desc+is%3Amerged+%22Synchronize+with+BCD%22+).

***
> I would also recommend thinking carefully about the wording of the banner

Feel free to create pull requests:
https://github.com/mdn/content/edit/main/files/en-us/mdn/writing_guidelines/experimental_deprecated_obsolete/index.md
https://github.com/mdn/yari/edit/main/kumascript/macros/SeeCompatTable.ejs

> "hey, this isn't in every browser yet..."

Even if every browser has the feature, but if it's behind flags or prefixes (e.g. `-webkit-`) then it is treated as experimental. [[ref](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#setting-experimental)]

Also there is a caveat, if only one browser has been supporting the feature by default for more than two years then it's not experimental. Concerns about this can be found [here](https://github.com/mdn/browser-compat-data/pull/17391#issuecomment-1217461467).
