### ISSUE TITLE
OWD project: @layers and cascade

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#94]
Cascade layers are part of [Interop 2022](https://web.dev/interop-2022/#cascade-layers)

[Cascade layers](https://developer.mozilla.org/docs/Web/CSS/@layer) give web developers more control over the cascade. They provide a way to group selectors into layers, each with its own specificity. Cascade layers are now supported in most, but not all, browsers. 

Cascade layers mean developers don't need to order selectors carefully or create highly specific selectors to overwrite base CSS rules. It also means there has been a change to the cascade. 

We have to:

* [x] Create a Cascade layers tutorial (new)
* [x] Rewrite [Introducing the CSS Cascade](https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade) to include Cascade layers
* [x] Rewrite [Cascade and inheritance](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance)
    * [x]  Live example on layers for tutorial  
* [x] Rewrite [CSS Cascade Skills test](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_tasks)
* [-] Add @layers to [CSS Custom Properties for Cascading Variables](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Variables)
* [x] Rewrite [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)
   * [x] include @layers impact on cascade
   * [x]  including proximity of elements
   * [x] explain specificity algorithm
* [x] Document [`!important`](https://developer.mozilla.org/en-US/docs/Web/CSS/important)

**Comment by dipikabh** [comment]
Hi @estelle, just a heads up to let you know that I will be working on the [@import](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) page for [issue#9369](https://github.com/mdn/content/issues/9369). I might also touch the [@layer](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer) page a bit. I can let you know when I am done in a day or two.
Hope that's okay with you and hopefully it will not conflict with your work on cascade layers.

**Comment by Elchi3** [comment]
This looks mostly done. Except for the leaning part. It has an open PR: https://github.com/mdn/content/pull/17723
Is anyone reviewing that?

**Comment by estelle** [comment]
It's still in draft mode.

**Comment by estelle** [comment]
Finished!
