### ISSUE TITLE
OWD project: Task-oriented content combining multiple APIs

### ISSUE THREAD

**Issue by dominiccooney** [openwebdocs/project#99]
Looking at 2022 Q2 Projects (Issue #95) I was speculating that MDN could write some intermediate/advanced tutorial or "architecture guide" content which cuts across multiple APIs.

To use Q2 projects as an example, something about implementing **themes** could combine CSS colors and cascade layers, plus some other APIs (prefers-color-scheme, CSS variables, maybe shadow parts.)

@estelle asked me to file this issue during last week's steering committee meeting. I'm not advocating a massive change of direction here: I really like MDN's comprehensive, individual-method-and-property level API documentation. But advanced material using different APIs together could have compelling value.

**Comment by Elchi3** [comment]
Closing this. We need concrete proposals or content drafts to showcase how certain APIs work together. This could be done by having a brainstorm session to draft such outlines or by doing user testing and user interviews. We are not planning to do that now. If there are concrete outlines for such content, please file a project proposal.
